include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Additional rules beyond flutter_lints
    avoid_print: false
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_pub_dependencies: true